services:
  acme-dns:
    image: joohoi/acme-dns:v2.0.2@sha256:8d327df58b1c9f6361c76734f9761a108fa4f12cf7ca94440a0404a28f75de62
    container_name: acme-dns
    restart: unless-stopped
    ports:
      - "116.202.22.50:53:53/udp"
      - "116.202.22.50:53:53/tcp"
    volumes:
      - ./config.cfg:/etc/acme-dns/config.cfg:ro
      - /data/acme-dns:/var/lib/acme-dns
    networks:
      - frontend
networks:
  frontend:
    name: frontend
    external: true