[[stack]]
name = "whoami-test"
description = "Stack test"
deploy = true
tags = ["test"]
[stack.config]
server = "Local"
git_provider = "github.com"
repo = "PortableStick/homelab-infra"
file_paths = ["hosts/vps-prod/stacks/whoami/compose.yaml"]