http:
  routers:
    immich-photos:
      rule: "Host(`photos.int.vindiesel.vip`)"
      entryPoints:
        - websecure
      service: home-vindiesel
      middlewares:
        - int-vpn
      tls: {}

    immich-pictures:
      rule: "Host(`pictures.int.vindiesel.vip`)"
      entryPoints:
        - websecure
      service: home-vindiesel
      middlewares:
        - int-vpn
      tls: {}

    pelican:
      rule: "Host(`mcwings.int.vindiesel.vip`)"
      entryPoints:
        - websecure
      service: home-vindiesel
      middlewares:
        - int-vpn
      tls: {}

    # mangetout : PUBLIC (backend app mobile) — pas de middleware int-vpn.
    mangetout-pb:
      rule: "Host(`pb.vindiesel.vip`)"
      entryPoints:
        - websecure
      service: home-vindiesel
      tls: {}

    mangetout-ai:
      rule: "Host(`ai.vindiesel.vip`)"
      entryPoints:
        - websecure
      service: home-vindiesel
      tls: {}

  services:
    home-vindiesel:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://100.65.11.58:80"

  middlewares:
    int-vpn:
      ipAllowList:
        sourceRange:
          - "100.64.0.0/10"
