name: immich1

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
    networks:
      - proxy
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.immich.rule=Host(`photos.int.vindiesel.vip`)"
      - "traefik.http.routers.immich.entrypoints=web"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "992"
    environment:
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_DATA_LOCATION: /data/immich-1/library/postgres
      UPLOAD_LOCATION: /data/immich-1/library
      IMMICH_VERSION: v2.7.5
      LIBVA_DRIVER_NAME: iHD
    env_file:
      - .env
    volumes:
      - /data/immich-1/library:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5-openvino@sha256:71cd5a681823c4b818f4b24b3f05816eccc3d085559e7615f695bde77e64f1f2
    networks:
      - backend
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "992"
    environment:
      MACHINE_LEARNING_DEVICE: GPU
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - type: tmpfs
        target: /cache
        tmpfs:
          size: 2147483648
    restart: always
    healthcheck:
      disable: false
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
    networks:
      - backend
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    env_file:
      - .env
    volumes:
      - /data/immich-1/library/postgres:/var/lib/postgresql/data
    tmpfs:
      - /tmp
      - /var/run/postgresql
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend:
    name: immich1_backend
  proxy:
    name: proxy
    external: true
